### ISSUE TITLE
Tracing: Self.Forward causes entirely new trace to be made

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/phobos-issues#13]
Version: 1.0.3

## Expected Behavior:

When an actor in the middle of processing a valid trace calls `Self.Forward`, it should be a continuation of the current trace in progress.

## Actual Behavior:

When `Self.Forward` is called, an entirely new trace is created.

**Comment by IgorFedchenko** [comment]
Some more info about tracing issues:

> This creates a new Span for the current Trace, or does it create a new Trace altogether?

>It creates a new trace.
>I’ve attached the screenshots from the traces and the spans for each traces. The execution order was the following.
>- MVC API level outside of Akka (Api_trace_flame  and Api_spans)
![Api_trace_flame](https://user-images.githubusercontent.com/9683660/98116213-0c5aea80-1eb9-11eb-8574-3676e43ea3df.jpg)
![Api_spans](https://user-images.githubusercontent.com/9683660/98116219-0ebd4480-1eb9-11eb-8543-3814c850d591.jpg)

>- Self.Forward (Trace-after-Self.Forward  and Span-after-Self.Forward)
![Trace-After-Self Forward](https://user-images.githubusercontent.com/9683660/98116286-21377e00-1eb9-11eb-89fb-712f5ab10a62.jpg)
![Span-After-Self Forward](https://user-images.githubusercontent.com/9683660/98116291-2268ab00-1eb9-11eb-8d4f-0bddbea8e250.jpg)
