### ISSUE TITLE
When using akka.serialize-messages = on together with Phobos it sometimes throws this error during shutdown

### ISSUE THREAD

**Issue by wesselkranenborg** [petabridge/phobos-issues#17]
[21:00:03.435 +02:00 Error] [Phobos.Actor.Instrumentation.Actors.EventStreamMonitorActor] [RequestId: ] Swallowing exception during message send
System.Runtime.Serialization.SerializationException: Failed to serialize and deserialize payload object [Phobos.Tracing.SpanEnvelope]. Envelope: [<Phobos.Tracing.SpanEnvelope> from [akka://blueprint-service/user/blueprint-actor_2bc365a3-12e4-4727-aaef-083b4f6f82d4#156300447]], Actor type: [Phobos.Actor.Instr
umentation.Actors.EventStreamMonitorActor]
 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Hyperion.SerializerFactories.ArraySerializerFactory.WriteValues<System.ValueType>(System.ValueType[], System.IO.Stream, System.Type, Hyperion.ValueSerializers.ValueSerializer, Hyperion.SerializerSession)' has s
ome invalid arguments

**Comment by Aaronontheweb** [comment]
Good to know - this must be an instance where the Phobos serializer hasn't been loaded for these traces, since those are supposed to be handled via a custom Protobuf serializer that Phobos injects. We'll look into this.

**Comment by Aaronontheweb** [comment]
I've been able to reproduce this same error using Newtonsoft.Json

**Comment by Aaronontheweb** [comment]
So the problem occurs when:

1. `akka.actor.serialize-messages =on`
2. Actor dies and produces a `DeadLetter` and that `DeadLetter` contains a [`SpanEnvelope`] (https://phobos.petabridge.com/api/Phobos.Tracing.SpanEnvelope.html)
3. `DeadLetter` gets wrapped inside another `SpanEnvelope`
4. Deserialization goes `SpanEnvelope` --> deserialize `DeadLetter` payload (uses the `Object` serializer) --> Attempts to deserialize `DeadLetter` payload as part of JSON graph

Right thing to do here is probably to unpack the inner `SpanEnvelope` that gets deadletter'd. That would solve the issue.
