### ISSUE TITLE
When support OpenTelemetry?

### ISSUE THREAD

**Issue by seungyongshim** [petabridge/phobos-issues#23]
Excuse, me.

Of course, I read to it.
>What About Phobos and OpenTelemetry?
In the near future Phobos will support the emerging OpenTelemetry standard, but as we noted earlier this summer - OpenTelemetry is still somewhat half-baked for .NET as of late 2020. We expect that by the time .NET 6 is released that OpenTelemetry will be widely available and ready for production use, at which point we will ensure that Phobos supports it.

But, currently, OpenTelemetry C# is Ver 1.0. 
So, I'm curious, when support OpenTelemetry?

I need to roadmap for my boss.

ps) Can Phobos support Splunk?

**Comment by seungyongshim** [comment]
Hello~

**Comment by Aaronontheweb** [comment]
Whoops, how did I miss this? Must have missed the email notification for this.

I answered this earlier today in the Akka.NET Gitter chat room, but the short version:

1. OpenTelemetry metrics support is still a work in progress and Prometheus is the only supported provider there - that's a major problem for our customers, many of whom use other platforms such as App Insights, DataDog, InfluxDB, and so on.
2. OTel can be supported in our tracing system today via the https://www.nuget.org/packages/OpenTelemetry.Shims.OpenTracing package, which is backwards compatible with anything that supports OpenTracing.

We would love to support OTel as it would solve an enormous number of issues for us and our users, but they need to get their act together on the metrics side of the equation so we have a suitable answer there. That's our current position. Hopefully with the approach of .NET 6, which includes BCL support for OTel, they will have some indication as to the progress they've made on the metrics piece.
