### ISSUE TITLE
How to disable tracing of Akka.Persistence messages?

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#54]
I am using latest Phobos 2.0 beta. I have the following configuration for Phobos tracing:

```
	tracing {
	    trace-all-system-actors = off
	    trace-all-user-actors = on
	    trace-actor-lifecycle = off
	    append-logs-to-trace = on
	}
```

When I run the application, I can see traces for all messages related to state recovery of persistence actors, like Akka.Persistence.ReplayedMessage, Akka.Persistence.RecoverySuccess etc., and this is indeed a huge amount of them.

We are not interested in them, and the only way to disable their tracing is to list all messages from Akka.Persistence, like this (code in F#):

```
        b.AddExcludeMessageFilter<Akka.Persistence.LoadSnapshot>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.LoadSnapshotResult>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.LoadSnapshotFailed>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.ReplayedMessage>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.ReplayMessages>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.ReplayMessagesFailure>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessages>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessageSuccess>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessagesSuccessful>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessagesFailed>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessageFailure>() |> ignore
        b.AddExcludeMessageFilter<Akka.Persistence.WriteMessageRejected>() |> ignore

```

Would it be reasonable to turn them off if trace-actor-lifecycle is off? Or introduce a new configuration variable?

**Comment by Aaronontheweb** [comment]
> Would it be reasonable to turn them off if trace-actor-lifecycle is off? Or introduce a new configuration variable?

Yes, we should disable Akka.Persistence tracing when `trace-actor-lifecycle` is off.

**Comment by object** [comment]
I am using the latest Phobos 2.0 beta. Do you suggest using b.AddCustomMessageFilter(filterRule) instead of AddExcludeMessage/AddIncludeMessage?

**Comment by Aaronontheweb** [comment]
ah no, if you're using the `AddExclude` / `AddInclude` message then you should be fine using the latest beta - sorry, I misread your comment.

**Comment by object** [comment]
But what I described above is a bug, right? trace-actor-lifecycle=off should have disabled all persistent state recovery messages?

**Comment by Aaronontheweb** [comment]
It's definitely a bug, or at the very least a configuration oversight on our part.

**Comment by Aaronontheweb** [comment]
This has now been fixed in 2.0.0 via the `phobos.tracing.trace-akka-persistence = off` setting. This will stop the journal and the snapshot store from recording any traces.

However, _your_ user-defined actors may still log the `WriteMessagesSuccessful` messages that they receive when processing events from the journal. Do you need us to filter those out as a well? That's a bit more intrusive but it can be done.

**Comment by Aaronontheweb** [comment]
Also, I would link to our documentation where it shows these settings but it's in the middle of being deployed right now 😅

**Comment by object** [comment]
@Aaronontheweb I tried the latest Phobos 2.0 package, and now I am getting roughly half of persistence messages when I set trace-akka-persistence = off. 

Without this filter I am getting the following messages:
1. First come Akka.Persistence.ReplayedMessage for each row in the event journal. They have actor path /system/akka.persistence.journal.sql-server
2. Upon the state recovery comes Akka.Persistence.RecoverySuccess
3. It is followed by a new set of Akka.Persistence.ReplayedMessage, this time with actor path of my persistent actor (e.g. /user/$e/potion:02b7ed7f-9a6f-40e3-b7ed-7f9a6f80e335)
4. Finally Akka.Persistence.RecoverySuccess is sent to my persistent actor

With trace-akka-persistence = off I am getting only message (3) and (4), sent to my persistent actor, the messages with actor path /system/akka.persistence.journal.sql-server are gone.

So I still need to explicitly exclude Akka.Persistence messages by specifying each unwanted message type. IMO the introduced switch is not working good enough - IMHO when we want to skip Akka.Persistence messages we want to filter them out completely.

**Comment by Aaronontheweb** [comment]
> So I still need to explicitly exclude Akka.Persistence messages by specifying each unwanted message type. IMO the introduced switch is not working good enough - IMHO when we want to skip Akka.Persistence messages we want to filter them out completely.

Ok, we'll do what we did for filtering out `DistributedPubSub` spam and add a built-in filter for this.

**Comment by object** [comment]
Cool. I will test it.

**Comment by object** [comment]
Works as it should, closing the issue.
