### ISSUE TITLE
Attempt to create a root span results in a child span

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#55]
I am trying to customize trace span hierarchy and create root spans in some places to start a logical span chain. To illustrate this on a simple example I chose the first lesson from Akka.NET Bootcamp where messages are sent between ConsoleReaderActor and ConsoleWriterActor. I customized ConsoleReaderActor code so it looks like this:

```
        protected override void OnReceive(object message)
        {
            var read = Console.ReadLine();
            if (!string.IsNullOrEmpty(read) && String.Equals(read, ExitCommand, StringComparison.OrdinalIgnoreCase))
            {
                // shut down the system (acquire handle to system via
                // this actors context)
                Context.System.Terminate();
                return;
            }

            var tracer = Context.GetInstrumentation().Tracer;
            using var rootSpan = tracer.StartRootSpan("reader.receive");

            //using var activity = ActivitySource.StartActivity("reader.receive", ActivityKind.Consumer);
            // send input to the console writer to process and print
            _consoleWriterActor.Tell(read);

            // continue reading messages from the console
            Self.Tell("continue");
        }

```

However, "reacer.receive" span is still created as a child of a ConsoleReader span "akka.msg.recv string", so all decisions to start new root spans is made by Phobos.

It is essential for us to be able to customize trace span sequence boundaries. Is this possible?

**Comment by object** [comment]
Or is this the consequence of https://github.com/open-telemetry/opentelemetry-dotnet/issues/2803?

**Comment by Aaronontheweb** [comment]
If it doesn't, that might be because we park the automatically generated active span inside a property into the `PhobosActorCell` and that still gets used by the `IActorRef.Tell` methods.

Worth noting:

```csharp
//using var activity = ActivitySource.StartActivity("reader.receive", ActivityKind.Consumer);
// send input to the console writer to process and print
_consoleWriterActor.Tell(read);
```

When you start a `RootSpan` in OTel, it's not automatically set as the new `Active` span - you have to explicitly set it as such:

```csharp
sp = Tracer.StartRootSpan(underlyingMsg.GetType().GetOperationName(),
                SpanKind.Consumer, InitialAttributes, startTime: startTime);
                
            Tracer.WithSpan(sp); // mark the current span as active
```

**Comment by Aaronontheweb** [comment]
I'll work on some repro specs for this

**Comment by object** [comment]
Tracer.WithSpan(rootSpan) makes the span root but that span remains isolated - it does not become a part of actors' span chain.

**Comment by Aaronontheweb** [comment]
Got it - I'll put a new snapshot test in for this scenario and see what we need to do differently to handle this scenario appropriately.

**Comment by Aaronontheweb** [comment]
@object this should be fixed in https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html#203-beta1-may-12th-2022
