### ISSUE TITLE
Custom span creation with Phobos 2.0.3-beta1

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#58]
I created a small repo to demonstrate the issues I am desciribing below:
https://github.com/object/AkkaWinTailWithPhobos

The repo is using WinTail sample from Akka.NET Bootcamp.

On start the root actor (ConsoleReader) receives a message "start" followed by user input.

User input in all tests consist of 4 strings:
123
456
7890
exit

**1. Default span creation (create-trace-upon-receive = on)**

Total spans: 7

```
akka.msg.recv start
    akka.msg.recv 123
    akka.msg.recv continue
        akka.msg.recv 456
        akka.msg.recv continue
	    akka.msg.recv 7890
            akka.msg.recv continue

```
This behavior is by design and can be replaced with manual span creation feature introduced in Phobos 2.0.3.

**2. No span creation (create-trace-upon-receive = off)**

ConsoleReader: No StartActiveSpan
ConsoleWriter: No StartActiveSpan

Total spans: 1

`akka.msg.recv start
`
Issues:
    - Why is the root span still created? Shouldn't all span creation be controlles by the application code?

**3. Manual span creation (create-trace-upon-receive = off)**

ConsoleReader: StartActiveSpan("ReadText", SpanKind.Consumer, Context.GetInstrumentation().UsableContext ?? default)
ConsoleWriter: StartActiveSpan("WriteText", SpanKind.Consumer, Context.GetInstrumentation().UsableContext ?? default)

Total spans: 7

```
akka.msg.recv start
    ReadText 123
    WriteText 123
    ReadText 456
    WriteText 456
    ReadText 7890
    WriteText 7890

```
Issues:
    - Same as previous one. Why is the root span still created?

In addition I would like to create ConsoleWriter spans as child spans for ConsoleReader, this is attempted in the next test.

**4. Manual span creation (create-trace-upon-receive = off)**

ConsoleReader: StartActiveSpan("ReadText", SpanKind.Consumer, Context.GetInstrumentation().UsableContext ?? default)
ConsoleWriter: StartActiveSpan("WriteText", SpanKind.Consumer, Context.GetInstrumentation().ActiveSpan)

Total spans: 4
Total spans: 1
Total spans: 1
Total spans: 1

```
akka.msg.recv start
    ReadText 123
    ReadText 456
    ReadText 7890
WriteText 123
WriteText 456
WriteText 7890

```
Issues:
    - Even though I try to set explicitly parent span for ConsoleWriter, all its spans are created as root spans.

**Comment by Aaronontheweb** [comment]
> - Why is the root span still created? Shouldn't all span creation be controlles by the application code?

ah, I think I know why this is - actor lifecycle tracing is still on. Guess I need to have that implicitly disabled when automatic span creation is turned off.

**Comment by Aaronontheweb** [comment]
That's a relief - in this case, this is still a bug in our implementation then. We're about to push a 2.0.3 that addresses https://github.com/petabridge/phobos-issues/issues/57 - I'll take another stab at fixing this once that's pushed.

**Comment by object** [comment]
@Aaronontheweb Do you have an ETA for this fix? Let me know if you need to validate the fix candidate.

**Comment by Aaronontheweb** [comment]
No ETA yet, been bogged down on a very weird Akka.Cluster.Sharding issue but I'll start looking into this tonight.

**Comment by Aaronontheweb** [comment]
> - Same as previous one. Why is the root span still created?

This is fixed - forgot to add an `if` statement to check to see if `create-trace-upon-receive = on` when an actor receives a message that has no active trace associated with it.

**Comment by object** [comment]
@Aaronontheweb Looks promising. Can you push a prerelease of 2.0.4 version of Phobos so I can also run some tests?

**Comment by Aaronontheweb** [comment]
I'm going to push 2.0.4 for real later today once I have a fix in-place for https://github.com/petabridge/phobos-issues/issues/59

**Comment by Aaronontheweb** [comment]
Phobos 2.0.4 is now live and should help resolve this issue: https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html#204httpssdkbincompublisherpetabridgeproductphobospackagesphobosactorversions204-june-02-2022

Give that a try and let us know if that solution works better for you.

**Comment by object** [comment]
Thanks @Aaronontheweb. Yes, I am writing some helper methods so the code will look more succinct, similar to what you suggested. I was at first confused that there is no TelemetrySpan - because in the output trace it looks like it is. But of course this is because I am now constructing it by hand from the context. So I can fully shape span topology. Makes sense.
