### ISSUE TITLE
Lots of noice in logging when using cluster sharding

### ISSUE THREAD

**Issue by gerardpeters** [petabridge/phobos-issues#59]
Hi,

I recently added phobos in production and I see a lot of log messages which seems to come from phobos.
![image](https://user-images.githubusercontent.com/5683331/171370385-37667535-3b24-43b9-b25d-ad518e1046be.png)

The all are logged under the same trace id. But I cannot find that particular trace anywhere in our traces.
An example of the details of one of those `message` logs:
![image](https://user-images.githubusercontent.com/5683331/171371397-76b4717c-4953-4825-8214-2f936871bfcc.png)

Is there a way to disable this logging? 

Phobos version: 2.0.3 with the use of Phbbos.Hosting. I do not have any other configuration of phobos in any hocon file.

**Comment by Aaronontheweb** [comment]
This sounds, to a degree, like Elastic doing the wrong thing with OTel data. But I could turn this logging off via settings in Phobos. I'll look into doing that.

**Comment by Aaronontheweb** [comment]
https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html#204httpssdkbincompublisherpetabridgeproductphobospackagesphobosactorversions204-june-02-2022 - Phobos 2.0.4 is now live and includes a new setting that should resolve this issue:

`phobos.tracing.log-message-events = on`, which when set to `off` will disable the creation of `waiting` and `message` events from being added to each automatically-created `akka.msg.recv` `TelemetrySpan`. This will greatly reduce the data footprint for each `TelemetrySpan` produced by Phobos and will help reduce the amount of noise generated on platforms like Elastic APM.

This setting is _enabled by default_ for all Akka.Cluster.Sharding actors so you probably don't need to do anything other than upgrade to the latest version. However, you can apply this setting to your entire `ActorSystem` or to individual actors if you wish. Please let us know if that resolves your issue!

**Comment by Aaronontheweb** [comment]
hi @gerardpeters , did this upgrade work for you?

**Comment by gerardpeters** [comment]
Yes, much appreciated! When I have the time I'll try to look into Elastic APM and the correlation of the messages but for now all looks good.
