### ISSUE TITLE
Stashing message may result in reset UsableContext

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#62]
I am investigating the issue that I first described here: https://github.com/petabridge/phobos-issues/issues/61

I have a scenario where a message is stashed, then unstashed and processed. A simplified workflow looks like this:

1. Actor A receives message M1
2. Actor A sends message M2 to actor B
3. Actor B receives message M2 in state B1
4. Actor B stashes message and goes to a state B2
5. Actor B unstashes all messages
6. Actor B receives message M2 in state B2
7. Actor B sends message M3 to actor C
8. Actor C receives message M3

When using default Phobos span creation, all stages above become spans in a single trace transaciton. When manually creating spans sometimes the trace transaction is broken in two depending on whether I create a manual span at certain point. Here what happens:

Scenario 1, correct behavior, single trace transaction

1. Actor A receives message M1
2. Manual span created
3. Actor A sends message M2 to actor B
4. Actor B receives message M2 in state B1
5. Manual span created
6. Actor B stashes message and goes to a state B2
7. Actor B unstashes all messages
8. Actor B receives message M2 in state B2
9. Manual span created
10. Actor B sends message M3 to actor C
11. Actor C receives message M3
12. Manual span created

Scenario 2, incorrect behavior, two trace transactions

1. Actor A receives message M1
2. Manual span created
3. Actor A sends message M2 to actor B
4. Actor B receives message M2 in state B1 - no manual span creation here!!!
5. Actor B stashes message and goes to a state B2
6. Actor B unstashes all messages
7. Actor B receives message M2 in state B2
8. Manual span created
9. Actor B sends message M3 to actor C
10. Actor C receives message M3
11. Manual span created

In the second scenario the first trace transaction is broken at (2), and the second trace transaction begins at (8).

**Comment by object** [comment]
The following example illustrates the problem:

```
    class ConsoleWriterActor : ReceiveActor, IWithUnboundedStash
    {
        public ConsoleWriterActor()
        {
            Even(true);
        }
        public IStash Stash { get; set; }

        private void HandleMessage(string msg)
        {
            if (string.IsNullOrEmpty(msg))
            {
                Console.ForegroundColor = ConsoleColor.DarkYellow;
                Console.WriteLine("Please provide an input.\n");
                Console.ResetColor();
                return;
            }

            var usableContext = Context.GetInstrumentation().UsableContext;
            using var mySpan = Context.GetInstrumentation().Tracer.StartActiveSpan("WriteText", SpanKind.Consumer,
                Context.GetInstrumentation().UsableContext ?? default);
            mySpan.SetAttribute("word", msg);

            // if message has even # characters, display in red; else, green
            var even = msg.Length % 2 == 0;
            var color = even ? ConsoleColor.Red : ConsoleColor.Green;
            var alert = even
                ? "Your string had an even # of characters.\n"
                : "Your string had an odd # of characters.\n";
            Console.ForegroundColor = color;
            Console.WriteLine(alert);
            Console.ResetColor();

        }

        private void Even(bool firstTime = false)
        {
            if (!firstTime)
                Stash.UnstashAll();
            Receive<string>(msg =>
            {
                if (msg.Length % 2 == 0)
                {
                    HandleMessage(msg);

                }
                else
                {
                    Stash.Stash();
                    Become(Odd);
                }
            });
        }

        private void Odd()
        {
            Stash.UnstashAll();
            Receive<string>(msg =>
            {
                if (msg.Length % 2 != 0)
                {
                    HandleMessage(msg);

                }
                else
                {
                    Stash.Stash();
                    Become(_ => Even(false));
                }
            });
        }
    }

```

**Comment by object** [comment]
In the example above stashing a message breaks the trace transaction.

**Comment by Aaronontheweb** [comment]
@object got it - looks like this is another edge case we need to handle differently around stashes. Stashed operations are a little unusual in that we typically capture the "live" span inside the stash and don't dispose it until it's finally processed. I'll need to see what we can do about handling that differently when automatic span creation is disabled.

**Comment by object** [comment]
@Aaronontheweb yes, it looks like span context is disposed when the message is stashed, and since stashing essential technique this needs to be resolved in order for manual span creation to work.

**Comment by Aaronontheweb** [comment]
I'll get right on it - as you can tell, there was quite a balancing act involved in making all of these edge cases work well with automatic span creation. Re-discovering all of that was we put the process into reverse.

**Comment by object** [comment]
Hmm, I don't know yet. My first thought is when creating spans manually all creation decisions should be in hands of the one managing spans so perhaps it should be turned off.

**Comment by Aaronontheweb** [comment]
Ok, I think I can manage that. If my reproduction spec I wrote for this issue passes with it, should be no big deal.

**Comment by Aaronontheweb** [comment]
Ok, that was trivially easy to manage. Will be shipping it without those spans being automatically created.

**Comment by object** [comment]
Great. Thanks for that. I will test it on Sunday.

**Comment by Aaronontheweb** [comment]
```csharp
    /// <summary>
    /// Reproduction spec for https://github.com/petabridge/phobos-issues/issues/62
    /// </summary>
    public class StashingNoAutomaticSpansSpec : PhobosSpec
    {
        public static readonly Config DisabledSpanCreationHocon = @"
           phobos.tracing.create-trace-upon-receive = off
        ";
        
        public StashingNoAutomaticSpansSpec(ITestOutputHelper helper) : base(DisabledSpanCreationHocon, helper)
        {
        }

        [Fact(DisplayName = "PhobosStash should preserve UsableContext when automatic span creation is disabled")]
        public async Task PhobosStash_should_preserve_UsableContext()
        {
            // arrange
            var myActor = Sys.ActorOf(Props.Create(() => new ActorWithUnboundedStash()), "unbounded-stash");
            
            // act
            using (var mySpan = Tracer.StartActiveSpan("StartSpan"))
            {
                myActor.Tell("stash");
            }
            myActor.Tell("unstash");
            
            // assert
            ExpectMsg<string>();

            await WaitForTracesToStabilize();
            
            LogSpansOnFail(() => CompletedActivities, x => x.Select(c => c.Context.TraceId).Distinct().Count().Should().Be(1));
        }

        private class ActorWithUnboundedStash : ReceiveActor, IWithUnboundedStash
        {
            private readonly ILoggingAdapter _log = Context.GetLogger();

            public ActorWithUnboundedStash()
            {
                Stashing();
            }

            public IStash Stash { get; set; }

            private void Stashing()
            {
                Receive<string>(str => str.Equals("unstash"), s =>
                {
                    Stash.UnstashAll();
                    _log.Info("Unstashing");
                    Become(Unstashed);
                });

                ReceiveAny(_ => Stash.Stash());
            }

            private void Unstashed()
            {
                ReceiveAny(_ =>
                {
                    _log.Info("Received {0}", _);
                    using var mySpan = Context.GetInstrumentation().Tracer.StartActiveSpan("MySpan",
                        parentContext: Context.GetInstrumentation().UsableContext ?? default);
                    Sender.Tell("ack_" + _);
                });
            }
        }
    }
```

This produces a single trace with 2 spans - does that look like it'll meet your requirements?

**Comment by object** [comment]
I am not at a computer now but it looks like what I need.

**Comment by Aaronontheweb** [comment]
Ok, we'll ship it.

**Comment by Aaronontheweb** [comment]
Hi @object 

Forgot to mention this, but we shipped this fix on Friday: https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html

**Comment by object** [comment]
@Aaronontheweb I tested it today, it works as expected.

**Comment by Aaronontheweb** [comment]
Glad to hear it!
