### ISSUE TITLE
Manually created trace spans don't seem to flow across the cluster

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#65]
I am using Phobos 2.0.6 and set "create-trace-upon-receive" flag to "off", so all trace spans are managed explicitly by the application. Application runs in an Akka cluster, and apparently when a message is sent to an actor running in a different cluster node (we use cluster sharding), the trace span created in a different node is not consolidated with the original one. If all actors runs in a single Akka actor system, then trace transaction looks correct and is not broken.

Needless to say that for us it's critical to create span transactions from messages sent between cluster nodes.

**Comment by Aaronontheweb** [comment]
We'll set up an integration test that uses Akka.Cluster.Sharding with `phobos.tracing.create-trace-upon-receive = off` and see if we can reproduce this. I think this might be an issue with sharding specifically.

**Comment by Aaronontheweb** [comment]
We think this issue is specific to how sharding works - spans are only designed to make it a single hop in Phobos.

**Comment by object** [comment]
I see. But when create-trace-upon-receive is on, then messages delivered using cluster sharding form trace transcations that spread across the cluster nodes, at least in some scenarios. So perhaps this just context propagation error for certain use cases (including create-trace-upon-receive=off).

**Comment by Aaronontheweb** [comment]
After @Arkatufus was able to reproduce this issue I've realized that this is a somewhat larger design problem when automatic span creation is turned off - actors that aren't manually programmed by the end-user can't create any spans so trace propagation stops.

We'll need to redesign it to function similarly to some of the remoting actors, which allow previous trace contexts to flow via `UsableContext`. This will be a slightly bigger design change but I think we can do it safely.

**Comment by object** [comment]
I suspected this could be related to span creation turned off. Let me know when you have something I can test. Next two weeks I will have more flexibility to work on this issue, so I can verify new version the same day you will release it.

**Comment by Aaronontheweb** [comment]
This is now resolved behind the scenes in Phobos 2.1.0-beta1 - there might be some cases where a trace gets broken the very first time a shard is allocated but there's not much we do can about that (`ShardRegion`'s custom message buffering breaks it, unless we allow a bunch of internal sharding messages to be automatically traced.) We also had to enable `create-trace-upon-receive = on` for `ShardRegion` and `ShardRegionProxy` even when it's disabled everywhere else - however, we were also able to trim quite a few system messages. Give 2.1.0-beta1 a try. The release notes should be live on https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html once our CI backlog is clear.

Please let us know if this helps resolve your issue.

**Comment by object** [comment]
@Aaronontheweb Is Phobos 2.1.0-beta1 released on NuGet? I tried to update the package but still got 2.0.6 as the latest version.

**Comment by Aaronontheweb** [comment]
Sigh, looks like it didn't get pushed right as I was signing off before going OOF. I'll get that fixed.

**Comment by Aaronontheweb** [comment]
Ah, looks like the version of Windows we were using in our release pipeline on AzDo was permanently deprecated. Ok, that's an easy fix. Shouldn't take long.

**Comment by Aaronontheweb** [comment]
Ok, these are all pushed to Sdkbin now!

**Comment by object** [comment]
Downloaded, will test.

**Comment by object** [comment]
Using Phobos 2.1.0-beta1 I can see that traces have spans from different cluster nodes. I need to inspect the content of trace transactions but for the time being I can confirm that Akka cluster sharding can be used with manually created spans.

**Comment by Aaronontheweb** [comment]
Good to hear!
