### ISSUE TITLE
When spans are created manually messages from cluster singleton break trace transactions

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#66]
This issue is similar to what was recently fixed for cluster sharding but this time the trace transactions are broken when there is a communication with a cluster singleton in the middle.

Here's our setup:

1. We use an open source library Akka.Persistence.Reminders written by Bartosz (https://github.com/Horusiath/Akka.Persistence.Reminders). It's been working very well for setting up long living reminders. Basically this library offers a persistent actor that stores messages and triggers their delivery to the specified actors when time comes.
2. The actor is set up as a cluster singleton so it is able to send messages across the cluster.
3. When setting up reminders the singleton receives a structure (actorPath, message, timeToTrigger) and an ack message. Ack is sent back to sender when the reminder is persisted. The sender awaits the ack and upon receiving it continues its work.

And here's what happens:

1. Actor A sends (actorPath, message, timeToTrigger) to a singleton reminder R (via singleton proxy) and waits for an ack
Trace scope:
parent.id: 2e3d95f72cb2e400
trace.id: 8b9a44351e0c0139135d2bee6c6ead9f
transaction.id: 041329dae121973d

2. Actor A receives an ack from reminder R
Trace scope:
parent.id: None
trace.id: 508caa2a51963c047f8b7fe4d7b24da1
transaction.id: b8038a327278c1f7

Note that parent.Id is None!

If I replace the cluster singleton with a fake reminder represented by a local actor that just forwards ack to the sender, then everything works and upon receiving ack parent.id points to a previous actor in a message chain and the trace transaction is not broken. This proves that the problem is with using a cluster singleton.

We are using most recent Phobos 2.1.0-beta1

**Comment by Aaronontheweb** [comment]
Got it - yeah this is going to be another instance of what we had to do to make sharding work. We'll get on it.

**Comment by Aaronontheweb** [comment]
Related: https://github.com/petabridge/phobos-issues/issues/65

**Comment by Aaronontheweb** [comment]
I wrote a reproduction this morning and everything worked fine using a ClusterSingletonManager / Proxy. This makes me wonder whether or not the issue is that the singleton replies back inside a `PersistAsync` block, which might break the manual propagation of traces here. Going to keep prodding my reproduction and see what I can come up with.

**Comment by Aaronontheweb** [comment]
So I think this is misnomer - the issue isn't cluster singletons as I've been able to validate that those work. It looks like the issue in this case is that the actor started by Akka.Persistence.Reminders doesn't have any manual instrumentation code for correlating spans, so automatic correlation needs to be turned on via configuration.

This can be accomplished via Phobos' HOCON or via the extension methods we apply to `Props`: https://phobos.petabridge.com/articles/setup/configuration.html#configuring-individual-actors-via-hocon-and-props - you can set 

```
akka.actor.deployment{
   /reminderSingleton/reminder
  {
    phobos.tracing.create-trace-upon-receive = on
  }
}
```

And that will enable it for that actor only.

**Comment by Aaronontheweb** [comment]
Give that fix a try and let me know if it doesn't solve the issue.

**Comment by object** [comment]
Thanks @Aaronontheweb, working with it now.

I checked the singleton path and it is "akka://Oddjob/user/rem:playabilitybump/singleton/rem:playabilitybump", so I assume I should specify "/rem:playabilitybump/singleton/rem:playabilitybump" in akka.actor.deployment section.

But I wonder why I need to turn it on. Because I set create-trace-upon-receive to off in our code, and I don't have any manual instrumentation for most of my actors, however spans get correlated.

Does this mean that it's not possible to use a 3rd party Akka.NET library when creating spans manually, unless create-trace-upon-receive is set ot on for actors from that library?

**Comment by object** [comment]
No, inserting akka.actor.deployment directive for the reminder actor didn't seem to help. What I will do I will fork the library and compile everything in our code base, then I will test again.

**Comment by Aaronontheweb** [comment]
> Does this mean that it's not possible to use a 3rd party Akka.NET library when creating spans manually, unless create-trace-upon-receive is set ot on for actors from that library?

Correct - that's why we designed Phobos to automatically create spans by default, as it's the only universal way to preserve context across all actors including ones not developed by the end-user directly.

**Comment by Aaronontheweb** [comment]
The HOCON _should_ allow you to manually override that for just that actor - you might also have to override it for the singleton proxies that send the message to the reminders actor as well. In that case I'd recommend just using the `Props.WithInstrumentation` extension method to do that:

```csharp
 var createTraceUponReceiveSettings = PhobosSettings.For(Sys).ActorSettings.WithCreateTraceUponReceive(true);

            var singletonProxyProps = ClusterSingletonProxy.Props("/user/echo-singleton",
                ClusterSingletonProxySettings.Create(_sys1).WithRole("backend").WithSingletonName("echo"))
                .WithInstrumentation(createTraceUponReceiveSettings);
            _singletonProxy = _sys1.ActorOf(singletonProxyProps, "echo-singleton-proxy");
```

I'd try that first before forking the library.

**Comment by object** [comment]
Thanks, I will give it a try. I already forked a lib but will try that suggestion too.

**Comment by object** [comment]
> > Does this mean that it's not possible to use a 3rd party [Akka.NET](http://Akka.NET) library when creating spans manually, unless create-trace-upon-receive is set ot on for actors from that library?
> 
> Correct - that's why we designed Phobos to automatically create spans by default, as it's the only universal way to preserve context across all actors including ones not developed by the end-user directly.

But I am using an external F# API lib Akkling with manually created spans. I wounder what the difference in that respect between Akka.Persistence.Reminders and Akkling.

**Comment by Aaronontheweb** [comment]
> But I am using an external F# API lib Akkling with manually created spans. I wounder what the difference in that respect between Akka.Persistence.Reminders and Akkling.

Ideally there shouldn't be much of one - everything Phobos does is at the `ActorCell` level, for the most part, which exists somewhat separately from the way the actors themselves are implemented by the end-user.

**Comment by object** [comment]
Related question: what if I wrap communication with a 3rd party actor in a local actor where I create manual spans? Now the message comes directly from a reminder and the context is not preseved. What if there is local reminder proxy that encapsulates all communication with a reminder singleton?

**Comment by Aaronontheweb** [comment]
As long as you have a data structure that can preserve the incoming `SpanContext` with either a new outgoing `SpanContext` or the original, it should work.

**Comment by object** [comment]
Let me experiment then with what will be most flexible to implement.

**Comment by object** [comment]
Hmm, I have built Akka.Persistence.Reminders together with my code, and still the trace transacation is broken at a call to a reminder proxy. I will continue investigating this.

**Comment by object** [comment]
I can confirm that if I replace the Akka.Persistence.Reminders scheduling actor with a fake non-persistent singleton, then everything works fine. Something is weird with Akka.Persistence.Reminders even though it's a simple persistent actor. Will experiment more.

**Comment by object** [comment]
This issue is not related to cluster singleton. I will continue investigating and when I find more I will create a new issue.

**Comment by Aaronontheweb** [comment]
Ok, thanks for letting us know @object
