### ISSUE TITLE
Does sending a message to sender from Persist/PersistAsync break trace transaction?

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#67]
I continue testing manual creation of trace spans. As I reported earlier, my problem is using Akka.Persistence.Reminder that has a schedule persistent actor. If the actor sends an ack to a sender after scheduling a message, the trace transaction breaks. The message to sender is sent from inside a PersistAsync call (I tried Persist with the same effect). If I remove Persist call and send Ack straight back to sender, then everything works.

So I suspected that the problem might lie in sending a message from a Persist closure argument. Akkling F# library has a similar technique of executing a closure after persisting a message but I never used it in my code. I changed my code from

`Persist event
`
to 

`Persist event |> Effects.andThen callback
`

This is an Akkling way of executing a callback handler after persisting an event. And the latter version broke the trace transaction.

I feel we are on a thin ice here. If this is the case that breaks transaction flow, I can understand that it can be hard if possible to fix it. On the other hand providing a closure for callback is quite normal scenario, and if a manual trace span management doesn't support such technique, then next question is whether manual trace span creation is worth at all. I am open for your judgement @Aaronontheweb, in the meantime I will think about possible workarounds. In case of Akka.Persistence.Reminder using such technique is a necessity because "sender" and "ack" only exist in the current scope.

**Comment by Arkatufus** [comment]
@object 
I've tried to reproduce the problem with `Persist`/`PersistAsync` and could not reproduce it.
`Akka.Persistence.Reminders` uses a `ReceivePersistentActor` internally. If you wanted to use manual span creation and are using `Akka.Persistence.Reminders`, you would have to create an internal fork of that project that manually create spans in its `Schedule` command handler.

**Comment by object** [comment]
I already forked it, will try to create manual spans there. I will also try to reproduce the problem in a smaller example.

**Comment by object** [comment]
I created small samples where I tested responding to sender from Persist/PersistAsync, and it worked fine. It also worked fine from a forked version of Akka.Persistence.Reminder. So it must be something else in my case. Sorry for a false alarm, closing this one.

**Comment by object** [comment]
@Aaronontheweb @Arkatufus 
I tested this situation more and here's what I've found:

1. The trace transaction breaks because UsableContext in a closure passed to Persist/PersistAsync may become null.
2. In a small test sample where I pasted the code of PersistentReminder actor, UsableContext in a closure wasn't null and the trace transaction was ok.
3. I forked Akka.Persistent.Reminders code, added it to my code base and created a custom span in PersistAsync closure. When creating this span I check whether UsableContext is null, and if so, then I use the instance of UsableContext obtained earlier in 
Command handler. This fixes the trace transaction.

I am puzzled why the same closure code works in a small sample and doesn't work in other code base. I even made sure both projects use same versions of key Nuget packages. Still different. I will come back to this problem, but in the mean time I will be using a forked version of Akka.Persistence.Reminder where I create a custom span  using previously saved UsableContext value.

**Comment by object** [comment]
And to make it more clear: Akka.Persistence.Reminder worked fine with a small example as it is, without forking and adding custom code. No need to create custom span in Reminder actor, UsableContext is retained. But in my code base I had to fork it and create a custom span inside Reminder actor PersistAsync closure, otherwise it started a new trace transaction.

**Comment by Aaronontheweb** [comment]
> I am puzzled why the same closure code works in a small sample and doesn't work in other code base. I even made sure both projects use same versions of key Nuget packages. Still different. I will come back to this problem, but in the mean time I will be using a forked version of Akka.Persistence.Reminder where I create a custom span using previously saved UsableContext value.

`UsableContext` is reset each time an actor's `Receive` method exits - which behind the scenes is what's happening when a `PersistentActor` is executing a `Persist` call - the lambda on that executes after the persist operation successfully completes is actually a separate and discrete message-processing interaction resulting from a message sent back from the journal. When automatic tracing is enabled all of this activity is correlated via the message interactions with the journal itself - that keeps everything contiguous in a single trace.

When automatic tracing is disabled, a user has to manually correlate those two activities together in order for the implementation to work now we're in user code rather than system code - we don't have any way from inside the Phobos instrumentation to tell what's happening at that layer since all we see is the `ActorCell` and the base class methods on the `IActorRef`. Does that make sense?

**Comment by object** [comment]
Yes, it makes sense, but doesn't this mean then that the lambda sent to Persist call should always lose the original UsableContext in manual span creation scenario? I am confused that it worked in a small sample. @Arkatufus also mentioned yesterday that he checked Persist/PersistAsync and could not reproduce the problem, I assume he was trying manual span creation. I have a workaround now, just curious (and want to understand it better).

**Comment by Aaronontheweb** [comment]
> but doesn't this mean then that the lambda sent to Persist call should always lose the original UsableContext in manual span creation scenario? 

yes it should - as that lambda is really a hidden second `Receive` statement, but it's triggered by `PersistentActor` base class code.

**Comment by object** [comment]
@Aaronontheweb @Arkatufus Apparently this can be sorted without forking external library (Akka.Persistence.Reminder in my case). I forgot about possibility to pass SpanContext. Indeed as long as I can create a new trace span using a previously saved instance of SpanContext, I can compose trace transaction exactly as I want it to be. So I just obtain ctx.GetInstrumentation().UsableContext and pass it to the places I want extend trace transaction with new spans.

**Comment by Aaronontheweb** [comment]
Thanks for following up with us @object - we really appreciate it. Glad you found a work-around for this.
