### ISSUE TITLE
Need to make all Akka.Cluster.Sharding infrastructure transparent in traces

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/phobos-issues#69]
Related https://github.com/petabridge/phobos-issues/issues/68

## Spec

The traces produced by Akka.Cluster.Sharding's infrastructure are not particularly interesting - we need a pass-through mechanism that allows messages to flow through the infrastructure, preserving their original traces, without having to record each of the separate hops made through `ShardRegion` / `Shard` / `ShardRegionProxy` actors.

This is akin to what we do with Akka.Remote - hide the trace inside the serialized message payloads and don't record the payloads themselves moving through the Akka.Remote infrastructure.

I believe this can be done by using our built-in wrapper types and the Akka.Cluster.Sharding infrastructure itself.

**Comment by Aaronontheweb** [comment]
Added a brief spec - going to work on prototyping some ideas for how to accomplish this @object

**Comment by ismaelhamed** [comment]
We are seeing an awful lot of messages like this:

```
Message [SpanEnvelope] from [akka.tcp://.../system/sharding/...#1815814387] to [akka://dlmshe/system/sharding/.../singleton/coordinator] was not delivered. [9] dead letters encountered. If this is not an expected behavior then [akka://dlmshe/system/sharding/.../singleton/coordinator] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by Aaronontheweb** [comment]
Now that Akka.NET v1.4.47 is out we're going to get the Phobos 2.1 release across the finish line. We'll resolve this issue as part of it.

**Comment by Aaronontheweb** [comment]
Related: https://github.com/petabridge/phobos-issues/issues/68#issuecomment-1359983582

**Comment by Aaronontheweb** [comment]
In sum, what we want to accomplish:

Traces that currently look like this

```mermaid
graph TD
  A[Actor1] --> B[ShardRegion1] -- remoting to Node2 --> C[ShardRegion] --> D[ShardId] --> E[EntityId]
```

Should look like this (ideally) instead

```mermaid
graph TD
  A[Actor1] --> E[EntityId]
```

**Comment by Aaronontheweb** [comment]
This has been resolved and will be released in Phobos 2.1, which we should ship shortly.

**Comment by object** [comment]
@Aaronontheweb when do you think Phobos 2.1 can be released?

**Comment by Aaronontheweb** [comment]
We actually just pushed the binaries live onto Sdkbin last night https://sdkbin.com/publisher/petabridge/product/phobos/packages/phobos.actor/versions/2.1.0

But the release notes aren't up live on the website yet. I'll paste them here so you can get the instructions for trace compression.

**Comment by Aaronontheweb** [comment]
We'll also be adding documentation on these features to the main Phobos website as well today, but we usually ship the binaries first.

**Comment by object** [comment]
Brilliant. Thank you so much.
