### ISSUE TITLE
Actor type information and F# API

### ISSUE THREAD

**Issue by object** [petabridge/phobos-issues#80]
Actor type information is very useful in Phobos metrics and traces, however when Akka.NET is used with F# API (either official Akka.NET F# API or Akkling OS library), all actors share the same type FunActor (in Akkling there is also FunPersistentActor for actors that impement persistence). FunActor is a generic type, but often its message type is set to "object" (to support processing of Akka system messages), so metrics and traces dashboards show just the same actor type for everything. In traces this can be somewhat improved when manually creating trace spans and passing span name.

There is not much to do about it as long as Phobos metrics and traces use whatever GetType() returns. But since the actor type is only needed to get the type name, perhaps Phobos can extend its metrics and tracing API to support customization of names used for actor types?

**Comment by Aaronontheweb** [comment]
Thanks for letting us know about this @object - you know, I wonder if I could expose a way to provide a custom type annotation of some kind for actors - maybe via an attribute or whatever. That should help support this case AND cases where a customer elected to track their actors using a different name than what we automatically generate.

**Comment by object** [comment]
Yes, I think it can be needed not only for F# case: same actor class can be used in different scenarios so it's good to separate between:
- Actor type
- Actor segment name in the Akka actor path
- Actor name as shown in Phobos instrumentation

Perhaps (2) can be used as replacement for (3), so it will be sufficient to set a name in the actor path that can be used in Phobos. But of course ability to cusomize actor presentation name will be the best.

**Comment by object** [comment]
No, using a segment from an actor's path is not a good idea. An actor can be a child of a router and its name won't give anything meaningful.

**Comment by Aaronontheweb** [comment]
This feature is now live in Phobos 2.6.0 https://sdkbin.com/publisher/petabridge/product/phobos/packages/phobos.actor/versions/2.6.0

Release notes will be live here in a few minutes https://phobos.petabridge.com/articles/releases/RELEASE_NOTES.html

**Comment by object** [comment]
That's a great news. We will try it ASAP.

**Comment by object** [comment]
I am afraid the PhobosActorName attribute won't help F# developers because it is applied on the actor class level, and both official F# API and Akkling create actors without defining classes: the actors are based on functions. Here's an example from an official Akka F# API:

```
let aref =
    spawn system "my-actor"
        (fun mailbox ->
            let rec loop() = actor {
                let! message = mailbox.Receive()
                // handle an incoming message
                return! loop()
            }
            loop())

```

The mailbox in this example belongs to an instance of an internal class FunActor shared by different actors, and they will still get the same Phobos name.

But can the name be customized by making possible via **IPhobosActorContext** available from **mailbox.UntypedContext.GetInstrumentation()**? The **IPhobosActorContext** has properties **Monitor** and **Tracer**. We are actively using **Tracer** to manage tracing, for example to start a new span (**tracer.StartActiveSpan**). **Monitor** property can be accessed to get the name of the underlying meter (**monitor.Name**). Is this the same name that can be customized using **PhobosActorName** attribute? If so, can the **Meter** class be extended with a name setter method, e.g. **SetName** which will apply it to the current instance of the meter?

**Comment by Arkatufus** [comment]
@object This is from @Aaronontheweb in Discord.

I’ll ask @Arkatufus to implement a version of this that accepts the type name as a ‘PhobosProps’ configuration argument instead of a type annotation
